spring:
  datasource:
    url: jdbc:mysql://localhost:3306/kotlin_demo?autoReconnect=true&useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&useSSL=false
    username: root
    password: root
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    show-sql: true
    properties:
      hibernate:
        format_sql: true

spring.jpa.properties.hibernate.dialect: org.hibernate.dialect.MySQL5Dialect

spring.jpa.hibernate.ddl-auto: update
---
spring:
  profiles: container
  datasource:
    url: jdbc:mysql://localhost:6603/kotlin_demo?autoReconnect=true&useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&useSSL=false
    username: root
    password: root
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    show-sql: true
    properties:
      hibernate:
        format_sql: true

